#!/bin/bash

echo "🚀 Setting up Neon DB for PrepLoot..."
echo ""
echo "After you update your DATABASE_URL in .env.local with your actual Neon connection string, run:"
echo ""
echo "1. Generate Prisma client:"
echo "   npx prisma generate"
echo ""
echo "2. Push schema to Neon DB:"
echo "   npx prisma db push"
echo ""
echo "3. Open Prisma Studio to view your database:"
echo "   npx prisma studio"
echo ""
echo "4. Start your development server:"
echo "   npm run dev"
echo ""
echo "✅ Your Neon DB will be ready for production use!"